name: Lint Markdown

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlintignore"
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlintignore"

jobs:
  markdownlint:
    name: Run markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ação oficial do autor do markdownlint-cli2 (rápida e simples)
      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
